// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl1_5lx9LeCK7gDfiC6JBctVJzM49NTM0',
    appId: '1:235217378200:web:21de203aae5de0cd5129ed',
    messagingSenderId: '235217378200',
    projectId: 'flutterapp-438b6',
    authDomain: 'flutterapp-438b6.firebaseapp.com',
    storageBucket: 'flutterapp-438b6.appspot.com',
    measurementId: 'G-L4587YK84J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_ULBsFs0WP1-9n_BAdSpKEDi9l-teDI',
    appId: '1:235217378200:android:7f9fc83afd8aeb0d5129ed',
    messagingSenderId: '235217378200',
    projectId: 'flutterapp-438b6',
    storageBucket: 'flutterapp-438b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJFM8ujkaIAYfK_5SMDwfzjIu52MfDXE',
    appId: '1:235217378200:ios:34426a56aff68d7f5129ed',
    messagingSenderId: '235217378200',
    projectId: 'flutterapp-438b6',
    storageBucket: 'flutterapp-438b6.appspot.com',
    iosClientId: '235217378200-s1e481jdt7ol366i3s4cmuv76gkprr43.apps.googleusercontent.com',
    iosBundleId: 'com.example.miPrimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJFM8ujkaIAYfK_5SMDwfzjIu52MfDXE',
    appId: '1:235217378200:ios:34426a56aff68d7f5129ed',
    messagingSenderId: '235217378200',
    projectId: 'flutterapp-438b6',
    storageBucket: 'flutterapp-438b6.appspot.com',
    iosClientId: '235217378200-s1e481jdt7ol366i3s4cmuv76gkprr43.apps.googleusercontent.com',
    iosBundleId: 'com.example.miPrimerApp',
  );
}
